### ISSUE TITLE
Problem 0 and # keys value

### ISSUE THREAD

**Issue by tuananhdn87** [AndrewMascolo/OnewireKeypad#8]
Hi, Im using 4x4 keypad, column registors are 1k, row registor are 4.7k, 1k to GND. 1 to * keys works perfectly, but two buttons (0 and #) return wrong char:
Press 0 button return 0 sometime # 
Press # button return D

what's wrong with me?

**Comment by tuananhdn87** [comment]
Solved, I change 1.9f in
`if (Reading <= (Vfinal + 1.9f )) {`
to 
`if (Reading <= Vfinal) {`

All buttons works.

**Comment by AndrewMascolo** [comment]
The constructor has a precision value, change it to fix your issue.
